name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create and activate virtual environment (Ubuntu)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest Flask

      - name: Run Tests (Ubuntu)
        run: |
          source venv/bin/activate
          pytest tests

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create and activate virtual environment (macOS)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest Flask

      - name: Run Tests (macOS)
        run: |
          source venv/bin/activate
          pytest tests

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create and activate virtual environment (Windows)
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest Flask

      - name: Run Tests (Windows)
        run: |
          .\venv\Scripts\Activate.ps1
          pytest tests
