name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies (Ubuntu)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests (Ubuntu)
        run: |
          source venv/bin/activate
          pip install pytest
          pytest app/tests

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies (macOS)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests (macOS)
        run: |
          source venv/bin/activate
          pip install pytest
          pytest app/tests

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests (Windows)
        run: |
          source venv/Scripts/activate
          pip install pytest
          pytest app/tests
